apiVersion: v1
kind: Service
metadata:
  name: fluentd-logging
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Fluentd"
spec:
  clusterIP: None
  ports:
    - name: forward
      port: 24224
      protocol: TCP
      targetPort: 24224
  selector:
    k8s-app: fluentd-logging
  sessionAffinity: None
  type: ClusterIP