apiVersion: apps/v1
kind: Deployment
metadata:
  name: coinbasepro-fh-btcusd
  labels:
    app: coinbasepro-fh-btcusd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coinbasepro-fh-btcusd
  template:
    metadata:
      labels:
        app: coinbasepro-fh-btcusd
    spec:
      containers:
        - name: coinbasepro-fh-btcusd
          image: cloudwallcapital/serenity:2021.01.17-b78
          command: ["/app/venv-py3/bin/python"]
          args: ["serenity/marketdata/fh/coinbasepro_fh.py", "--include_symbol=BTC-USD"]
          env:
            - name: POSTGRES_SERENITY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret-config
                  key: serenity-password
          volumeMounts:
            - mountPath: /behemoth
              name: behemoth 
      volumes:
        - name: behemoth
          persistentVolumeClaim:
            claimName: behemoth-pv-claim
