api-version: v1Beta
feedhandlers:
  - exchange: Phemex
order_placers:
  - exchange: Phemex
environment:
  - key: EXCHANGE_INSTANCE
    value-source: SYSTEM_ENV
  - key: PHEMEX_API_KEY
    value-source: SYSTEM_ENV
  - key: PHEMEX_API_SECRET
    value-source: SYSTEM_ENV
strategies:
  - name: Peg
    module: peg
    strategy-class: Peg
    environment:
      - key: PEG_INSTRUMENT
        value: BTCUSD
      - key: PEG_TYPE
        value: Near
      - key: PEG_SIDE
        value: Buy
      - key: PEG_QTY
        value: 1
